# .github/workflows/build.yml
name: Java CI (Maven)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  create-folder:
    name: create-folder
    runs-on: ubuntu-latest
    steps:
      - name: Create folder on remote VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host:     ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port:     ${{ secrets.PORT }}
          key:      ${{ secrets.PRIVATE_KEY }}
          script: |
            whoami
            mkdir -p /opt/myapp
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      # ⚠️ Enlève -DskipTests quand tes tests seront prêts
      - name: Build with Maven
        run: mvn -B -DskipTests clean package

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar
