# .github/workflows/build.yml
name: Java CI (Maven)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  create-folder:
    name: create-folder
    runs-on: ubuntu-latest
    steps:
      - name: Create folder on remote VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host:     ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port:     ${{ secrets.PORT }}
          key:      ${{ secrets.PRIVATE_KEY }}
          script: |
            whoami
            mkdir -p /opt/myapp

  build-and-deploy:
    name: build-and-deploy
    runs-on: ubuntu-latest
    needs: create-folder            # ← attendre la création du dossier sur le VPS
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build with Maven (skip tests for now)
        run: mvn -B -DskipTests clean package

      - name: Rename jar to app.jar (facultatif mais pratique)
        run: |
          JAR=$(ls target/*.jar | head -n1)
          cp "$JAR" target/app.jar
          ls -lh target/

      # === Déploiement sur le VPS par SCP (clé privée) ===
      - name: Copy JAR to VPS via SCP
        uses: appleboy/scp-action@v1.0.0
        with:
          host:     ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port:     ${{ secrets.PORT }}
          key:      ${{ secrets.PRIVATE_KEY }}   # ← pas de PASSWORD ici
          # chemins vus depuis le runner GitHub:
          source:   "target/app.jar"
          # dossier de destination sur le VPS (créé par le job précédent)
          target:   "/opt/myapp/"

      # (Optionnel) Vérifier côté VPS
      - name: Verify file on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host:     ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port:     ${{ secrets.PORT }}
          key:      ${{ secrets.PRIVATE_KEY }}
          script: |
            ls -lh /opt/myapp/app.jar
