# .github/workflows/build.yml
name: Java CI (Maven)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  create-folder:
    name: create-folder
    runs-on: ubuntu-latest
    steps:
      - name: Create folder on remote VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host:     ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port:     ${{ secrets.PORT }}
          key:      ${{ secrets.PRIVATE_KEY }}
          script: |
            mkdir -p /opt/myapp

  build-and-deploy:
    name: build-and-deploy
    runs-on: ubuntu-latest
    needs: create-folder
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build with Maven (skip tests for now)
        run: mvn -B -DskipTests clean package

      - name: Rename jar to app.jar
        run: |
          JAR=$(ls target/*.jar | head -n1)
          cp "$JAR" app.jar        # <<== note : on place à la racine du workspace
          ls -lh app.jar

      - name: Copy JAR to VPS via SCP
        uses: appleboy/scp-action@v1.0.0
        with:
          host:     ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port:     ${{ secrets.PORT }}
          key:      ${{ secrets.PRIVATE_KEY }}
          source:   "app.jar"           # fichier direct, pas target/...
          target:   "/opt/myapp/app.jar" # chemin final exact

      - name: Verify file on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host:     ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port:     ${{ secrets.PORT }}
          key:      ${{ secrets.PRIVATE_KEY }}
          script: |
            ls -lh /opt/myapp/app.jar
